name: Build and Deploy order-options-simplified to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (subproject)
        run: npm ci
        working-directory: VUE-comp/order-options-simplified

      - name: Build subproject
        run: npm run build
        working-directory: VUE-comp/order-options-simplified

      - name: Deploy to gh-pages under VUE-comp/order-options-simplified/
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Use token for pushing
          git remote set-url origin "https://x-access-token:${REPO_TOKEN}@github.com/${{ github.repository }}.git"

          # Fetch gh-pages if it exists
          git fetch origin gh-pages || true

          if git rev-parse --verify origin/gh-pages >/dev/null 2>&1; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git rm -rf . || true
            git clean -fdx || true
            git commit --allow-empty -m "Init gh-pages" || true
          fi

          # Remove previous folder for this app and copy fresh build
          rm -rf VUE-comp/order-options-simplified
          mkdir -p VUE-comp/order-options-simplified
          cp -R VUE-comp/order-options-simplified/dist/* VUE-comp/order-options-simplified/

          git add VUE-comp/order-options-simplified
          git commit -m "Deploy order-options-simplified" || echo "No changes to commit"
          git push origin gh-pages --force
